version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: grid_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: grid
      POSTGRES_PASSWORD: grid8
      POSTGRES_DB: grid
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
